name: nojs-verify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate-issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - id: validate-issue
        env:
          ISSUE_NUM: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "Issue #$ISSUE_NUM, candidate $ISSUE_TITLE"

          regex='^(https?|http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]\.[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$'
          if [[ $ISSUE_TITLE =~ $regex ]]
          then
            echo ::set-output name=comment::"URL is valid, will update the website shortly."
          else
              echo ::set-output name=comment::"URL is invalid, edit and update issue to a valid URL."
          fi
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if:
        with:
          issue-number: $ISSUE_NUM
          body: ${{ steps.validate-issue.outputs.comment }}


