name: nojs-verify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ISSUE_NUM: ${{ github.event.issue.number }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate-issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: validate-issue
        shell: bash
        run: |
          echo "Issue #$ISSUE_NUM, candidate $ISSUE_TITLE"

          regex='^(https?|http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]\.[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$'
          if [[ $ISSUE_TITLE =~ $regex ]]
          then
            domain=$(echo $ISSUE_TITLE | awk -F/ '{print $3}')
            if grep -Fq "$domain," _data/sites.csv; then
                echo ::set-output name=comment::"$domain already exists in data."
                exit 1
            else
              js_out=$(curl -sSL $domain | grep -F '<script')
              if [ -z "$js_out" ]; then
                echo ::set-output name=comment::"URL is valid and no javascript found, will update the website shortly."
              else
                body="URL is valid, but Javascript was found:\n
                \`\`\`$js_out\`\`\`"
                body="${body//'%'/'%25'}"
                body="${body//$'\n'/'%0A'}"
                body="${body//$'\r'/'%0D'}"
                echo ::set-output name=comment::$body
                exit 1
              fi

            fi
          else
              echo ::set-output name=comment::"URL is invalid, create a new issue with a valid URL in title (eg: `https://example.com`)."
              exit 1
          fi

      - name: Close Issue
        if: ${{ failure() }}
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ env.ISSUE_NUM }}
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: ${{ steps.validate-issue.outputs.comment }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ env.ISSUE_NUM }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.validate-issue.outputs.comment }}

  # This workflow contains a single job called "build"
  update-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: validate-issue
    if: ${{ success() }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Runs a set of commands using the runners shell
      - id: get-size
        shell: bash
        run: |
          size=$(curl -sSL $ISSUE_TITLE | wc -c | awk '{print $1/1000}')
          domain=$(echo $ISSUE_TITLE | awk -F/ '{print $3}')
          echo ::set-output name=size::$size
          echo ::set-output name=domain::$domain

      - name: Update repo data
        shell: bash
        run: |
          echo "${{ steps.get-size.outputs.domain }},${{ steps.get-size.outputs.size }}" >> _data/sites.csv

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add ${{ steps.get-size.outputs.domain }}, #${{ env.ISSUE_NUM }}"

      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ env.ISSUE_NUM }}
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: Site added to data. Will be live on https://nojs.club soon.
